//Category Types

// export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
// export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
