//Category Types

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";

// INEGREDIENT
// export const DELETE_INEGREDIENT = "DELETE_INEGREDIENT";
export const CREATE_INEGREDIENT = "CREATE_INEGREDIENT";
// export const UPDATE_INEGREDIENT = "UPDATE_INEGREDIENT";
export const FETCH_INEGREDIENT = "FETCH_INEGREDIENT";
