//Category Types

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";

// INEGREDIENT
export const CREATE_INEGREDIENT = "CREATE_INEGREDIENT";
export const FETCH_INEGREDIENT = "FETCH_INEGREDIENT";

// RECIPE
export const CREATE_RECIPE = "CREATE_RECIPE";
export const FETCH_RECIPE = "FETCH_RECIPE";
